### ISSUE TITLE
Symfony 3.2

### ISSUE THREAD

**Issue by ducho** [omines/datatables-bundle#1]
Hi.  
I would like to use your bundle, but is really necessary to upgrade Symfony to 3.3?

**Comment by curry684** [comment]
First of all thank you for your interest in our project!

It was a conscious decision on our end to target only [actively maintained Symfony](https://symfony.com/roadmap) versions. Having said that, we did look into lowering the minimum requirements as far as we could, but came to the conclusion this would mean a lot of changes as we're actively using the new [Symfony 3.3 DI container features](https://symfony.com/doc/current/service_container/3.3-di-changes.html). Changes we were not keen on making just to support an end of life version, and we also do not deem necessary as we have not had any real trouble at all upgrading any of our own applications to 3.3 from 3.x thanks to [Symfony's BC promise](https://symfony.com/doc/current/contributing/code/bc.html).

Summarizing: yes, the upgrade is necessary, but likely painless on your end.

As a sidenote, while you're welcome to use the bundle already, you should be aware that we're still doing initial development in `master`, as noted in the README. Therefore the bundle is not fit for production use right now. We do plan on releasing a 0.1 version soon-ish as we do feel comfortable with the current public API.

**Comment by curry684** [comment]
I've been hard at work to stabilize the API, feel free to have a look and provide feedback on things you'd like to see or think we did wrong   😄

**Comment by curry684** [comment]
Took somewhat longer than expected to refactor, but [we're stable](https://github.com/omines/datatables-bundle/releases/tag/0.1.0)   :)
