### ISSUE TITLE
Passing variables 

### ISSUE THREAD

**Issue by polo195pl** [omines/datatables-bundle#102]
How can i pass variable into TwigColumn?

**Comment by polo195pl** [comment]
Variables is auto passing. You can check in twig via `{{ dump() }}`

**Comment by curry684** [comment]
Curious - was the documentation on this unclear?

https://omines.github.io/datatables-bundle/#twigcolumn

**Comment by norbert-n** [comment]
Its not unclear, but for me it looks like a workaround if i need to pass a controller variable to the template.
now i have to inject the twig environment in my controller action and call
`$twig->addGlobal('name', $variable );`
It would be nice to just have
```
$table->add(
            'name',
            TwigColumn::class,
            ['variables' => ['name' => $variable],
...
```
or something like that
