### ISSUE TITLE
Column search not work

### ISSUE THREAD

**Issue by teamwork-it** [omines/datatables-bundle#107]
Hello,

I use Omines bundle 0.3.0, i use it for display a entity listing on page and it's work fine.
I have a problem when i try to use filter on specific column.
`.then(function(dt) {
            dt.page.len(25).draw();
                $("body").on("click","#showAll",function(e){
                    if ($(this).is(':checked')){
                        dt.search('').draw();
                    }else {
                       dt.columns(1).search(1).draw();
                    }

                });
        });`
The ajax query is sent with good param in column 1 ==> columns[1][search][value] | 1
but the return results are not filtered, all results are returned.
**i know i am not the first to meet this problem but there is never anwser so plesae not close or delete my post.**

**Comment by shades684** [comment]
Basically we haven't implemented this like said in issue #2 

You can implement this though because the value is still being send to the server, you could read the request variable and use it in a custom criteria provider.

**Comment by vaibhavpandeyvpz** [comment]
I have proposed a PR for this #120

**Comment by curry684** [comment]
Closing as #2 already describes the feature request and #120 proposes a fix.
