### ISSUE TITLE
Latest version of doctrine/doctrine-bundle breaks ORMAdapter.php

### ISSUE THREAD

**Issue by henry1303** [omines/datatables-bundle#108]
Upgrading doctrine/doctrine-bundle from 1.12.0 to 2.0.0 is breaking omines/datables-bundle because ORMAdapter.php is using RegistryInterface instead of ManagerRegistry. Could you please fix this ?

**Comment by Nathan-Riviere** [comment]
Hello, I have the same problem.

**Comment by curry684** [comment]
Fixed in master by #110
