### ISSUE TITLE
Twig_Environment

### ISSUE THREAD

**Issue by Nathan-Riviere** [omines/datatables-bundle#111]
Upgrading twig/twig to 2.11.3.

> Argument 1 passed to Omines\DataTablesBundle\Twig\TwigRenderer::__construct() must be an instance of Twig_Environment or null, instance of Twig\Environment given, called in /var/www/[...]/var/cache/dev/ContainerCsvvUZ2/getDataTableFactoryService.php on line 14

Could you please fix this ?

**Comment by curry684** [comment]
Should be fixed in master now with #109
