### ISSUE TITLE
Symfony 5 compatibility?

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [omines/datatables-bundle#113]
Is this package compatible with Symfony 5?

**Comment by MaximePinot** [comment]
Not yet. It will be compatible when these two PRs are merged (and composer.json updated): #110 and #109.

**Comment by vaibhavpandeyvpz** [comment]
OK. I am inline.

**Comment by vaibhavpandeyvpz** [comment]
@curry684 Since you bumped the dependencies I saw, would you mind tagging it.

**Comment by curry684** [comment]
You do not want that until I fixed everything to work with the new dependencies.

**Comment by vaibhavpandeyvpz** [comment]
I cannot do my project further until its updated so please forgive my eagerness. Please take your time.

**Comment by curry684** [comment]
Wise lesson for the next time - do not upgrade to a new Symfony major version until it's been out for at least 3 months so dependencies have caught up   😉

**Comment by curry684** [comment]
You should be able to test `dev-master` right now. Keep me posted if you see anything unexpected.

**Comment by vaibhavpandeyvpz** [comment]
OK. Giving it a try.

**Comment by curry684** [comment]
No weird stuffs? I'm getting 2 worrying errors out of the unit tests I can't really explain.

**Comment by curry684** [comment]
Fixed those, still got a bunch of crashes in unit tests but non-functional.

https://github.com/omines/datatables-bundle/releases/tag/0.4.0

Submit issues (or preferably PRs) if you find anything.

**Comment by vaibhavpandeyvpz** [comment]
@curry684 Its working great with Symfony 5 and I came back to thank you and the contributors for creating such a great package that saves time while maintaining project structure. Its one of of the most useful package even to me.

**Comment by curry684** [comment]
Thanks, highly appreciated   😄 

Happy new year!

**Comment by vaibhavpandeyvpz** [comment]
HNY to everyone! 🎆
