### ISSUE TITLE
JS events (draw|init) does not fire when language translations are included

### ISSUE THREAD

**Issue by jkabat** [omines/datatables-bundle#136]
Translations provided in options create conflict with JS datatables events. I'm not sure if the issue is caused by contents of translation keys or it is known issue with JS library.
Unfortunately locale in format 'fr_FR' forces Symfony translations instead of CDN URL.

One possible solution can be: 
```php
$locale = $this->translator->getLocale();
$locale = \Locale::getPrimaryLanguage($locale);
```

**Comment by curry684** [comment]
@freezy-sk does this stem from https://github.com/omines/datatables-bundle/pull/130?

**Comment by curry684** [comment]
@jkabat can you elaborate more on the symptoms, do you get errors in the JS console?

**Comment by jkabat** [comment]
No, there are no errors. DT events in .then{} part of Promise simply does not fire. They are fired properly when CDN translations are used.

**Comment by curry684** [comment]
Uh no clue then, waiting on @freezy-sk feedback.

**Comment by freezy-sk** [comment]
@curry684 I think that update of translations can't cause this issue.
@jkabat could you please verify if it works correctly with 0.4.0?

**Comment by jkabat** [comment]
I'm using latest tagged version. I think #130 is not yet included in it, so issue is caused either by translations bundled with tagged version or by datatables JS library itself.

**Comment by freezy-sk** [comment]
@curry684 I've made simple test #139 to check if translations are rendered and escaped correctly and it looks ok

**Comment by curry684** [comment]
Hmm indeed #130 is not tagged yet. If the language files are bugging out it might actually fix it as well. Can you try with `dev-master` @jkabat ?

**Comment by jkabat** [comment]
Actually it was frontend issue, sorry for spamming.

I've changed daterangepicker init from:
```js
 $(this.selector).each(function(index) {
```
to
```js
$('body').on('focus', this.selector, function() {
```
