### ISSUE TITLE
ORMAdapter Error

### ISSUE THREAD

**Issue by Xeyos88** [omines/datatables-bundle#148]
Hello,
after following the various steps, and also having some problems in managing client dependencies with webpack. I have the following error:

> Argument 1 passed to Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given

And this is my code:
```php
$table = $dataTableFactory->create()
            ->add('title', TextColumn::class)
            ->add('created_at', DateTimeColumn::class)
            ->createAdapter(ORMAdapter::class, [
                'entity' => Article::class,
            ]);
```
Where am i wrong?

**Comment by giovannialbero1992** [comment]
I think that it is a problem with Symfony's Dependency Injection. Check if it is declared a service `Symfony\Bridge\Doctrine\RegistryInterface` .

**Comment by curry684** [comment]
Which versions of Symfony and our bundle are you using?

This stems from a deprecation in Symfony which was fixed in [0.4.0](https://github.com/omines/datatables-bundle/releases/tag/0.4.0) 4 months ago.

**Comment by curry684** [comment]
Specifically it was fixed by https://github.com/omines/datatables-bundle/pull/110.

**Comment by Xeyos88** [comment]
I use symfony 4.4

**Comment by curry684** [comment]
> and our bundle

**Comment by curry684** [comment]
You may actually be using a f*bar combination of `symfony/doctrine-bridge`, `doctrine/doctrine-bundle` and `omines/datatables-bundle` versions which we cannot easily fix (problem on Symfony's end). Please list versions of all those 3 dependencies.

And ensure a simple `composer upgrade` does not fix your issue, your Symfony version is also 3 minors behind.

**Comment by curry684** [comment]
No feedback, assuming fixed.
