### ISSUE TITLE
Raw label markup

### ISSUE THREAD

**Issue by B2F** [omines/datatables-bundle#149]
From the doc, the TextColumn class accepts a raw options but this option doesn't seem to work with labels, only rendered content ...

Am I mistaking ? Isn't it possible to add html tags in the table headers (th) ?

**Comment by curry684** [comment]
Right now indeed it isn't. W3C specs do allow flow content in `th` elements but in general I would advise against it when using DataTables as it's doing a lot of magic with the headers on its own.

**Comment by B2F** [comment]
Ok thanks I think we'll do the trick in Javascript then.

**Comment by curry684** [comment]
Okies, I'm not really tempted to add a feature for it in core and we can't change it outright for BC reasons  👍
