### ISSUE TITLE
Datatable return request for data not returning with GET parameters

### ISSUE THREAD

**Issue by adsazad** [omines/datatables-bundle#153]
I am using datatable. and i added a parameter in url for some work but when datatable returns to url for data it returns without GET parameters. I am also not able to find any function to inject parameters into return request.

**Comment by curry684** [comment]
Ok, so what's the issue?

**Comment by adsazad** [comment]
I have a page /list?status=true and i want to send that same status to the request which come back for data for datatable

**Comment by curry684** [comment]
Sorry I still have no idea what you are asking about. Please elaborate, with details on:
* What are you trying to do
* How are you trying to do it
* Why is it not working
* Why is that this bundle's fault
* What do you propose to change

**Comment by adsazad** [comment]
I have a route /admin/list in which i have a optional parameter status which maked /admin/list?status=open.
Page runs but when it retrives data from from the page it does not send request to the page with the same parameters

**Comment by MaximePinot** [comment]
Wouldn’t it be better to replace https://github.com/omines/datatables-bundle/blob/ed00d890cc471671b615484d8e2873e3b6a8521e/src/Resources/public/js/datatables.js#L127 

by 

```javascript
url: window.location.href
```

**Comment by adsazad** [comment]
will this be working for response required by the omines datatable.

**Comment by curry684** [comment]
> Wouldn’t it be better to replace
> 
> https://github.com/omines/datatables-bundle/blob/ed00d890cc471671b615484d8e2873e3b6a8521e/src/Resources/public/js/datatables.js#L127
> 
> by
> 
> ```js
> url: window.location.href
> ```

They're not equivalent - I wrote it like this specifically to avoid duplicate/conflicting parameters. If the `href` is `somepace?a=b#anchor` this would break things spectacularly.
