### ISSUE TITLE
Tag Release

### ISSUE THREAD

**Issue by michaelotoole** [omines/datatables-bundle#155]
Any chance of an updated release to get rid of those pesky Ambiguous class resolutions from symfony/contracts?

Thanks :)

**Comment by curry684** [comment]
https://github.com/omines/datatables-bundle/releases/tag/0.5.0-rc.1

Removing the RC when the tests are passing again hehe.

**Comment by curry684** [comment]
Requested @MaximePinot for help in this, it's coming from #83

**Comment by MaximePinot** [comment]
#168 fixes tests concerning the service-side export feature.

**Comment by curry684** [comment]
There ya go: https://github.com/omines/datatables-bundle/releases/tag/0.5.0
