### ISSUE TITLE
addSelect with my own 'as' statement not working.

### ISSUE THREAD

**Issue by adsazad** [omines/datatables-bundle#161]
I am trying to add addSelect with sum() function and an 'as' statement. but it doesn't work.
It Gives Out `Field name 'xyz' must consist at least of an alias and a field separated with a period`

My Code:
`$builder->select('u')
                 ->addSelect('sum(s.id) as xyz')
                 ->from(User::class, 'u')
                ->leftJoin(\App\Entity\Score::class, 's', \Doctrine\ORM\Query\Expr\Join::WITH, 's.scoredTo = u.id') ;`

My Field:
`
->add('score', TextColumn::class, ['label' => 'Scores', 'field' => 'xyz'])
`

**Comment by curry684** [comment]
I believe your issue is more with DQL than with our bundle in this case: https://stackoverflow.com/a/54046848/1729885

**Comment by adsazad** [comment]
My DQL is giving result but when it use with the datatable.
it dose't not work.

**Comment by curry684** [comment]
Of course it gives results, it's just no longer an ORM result as you are querying properties not belonging to objects, hence deviating from the 'Object Relation Mapping' concept. Doctrine provides such results in arrays, and this bundle currently does not handle them natively, so in practice you need to provide your own `render` methods then.

**Comment by adsazad** [comment]
my question is just that how to add select with as avoiding this error
`Field name 'xyz' must consist at least of an alias and a field separated with a period`

**Comment by adsazad** [comment]
` ->addSelect('sum(s.id) as xyz')`

**Comment by MaximePinot** [comment]
Remove the `field` option from your column definition and use the `render` option.

Something like this:

```php
$dataTable->add('xyz', TextType::class, [
	'orderField' => 'xyz',
	'render' => static fn(string $value, array $context) => $context['xyz'],
]);
```

Also, set the `hydrate` option to `Query::HYDRATE_ARRAY` :
https://github.com/omines/datatables-bundle/blob/7842f2e91c0c077b6589bf616a396b22a443b7d7/tests/Fixtures/AppBundle/Controller/PlainController.php#L58-L61
