### ISSUE TITLE
How to add a checkbox in the header like this

### ISSUE THREAD

**Issue by ridjy** [omines/datatables-bundle#172]
$dataTableFactory->create()
            ->add('selection', TextColumn::class, ['label' => '
`<input type="checkbox" name="selectAll" id="selectAll">`
'])

**Comment by curry684** [comment]
Raw markup is not supported in non-content fields, use Javascript to find and decorate the headers instead.

**Comment by ridjy** [comment]
Thanks for your reply, I've done this in javascript and it's ok

**Comment by curry684** [comment]
👍
