### ISSUE TITLE
How to work with ManyToMany case??

### ISSUE THREAD

**Issue by chanondb** [omines/datatables-bundle#181]
I can work on case like simple single One to Many relation is all good.

But as we need to do multi-lang like translations(KNP Translations) or  one product can be in many Categories (ManyToMany)

/**
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="products")
     * @ORM\JoinTable(name="product_has_categories")
     * @ORM\OrderBy({"categoryOrder" = "ASC"})
     */
    private $categories;

Any suggestions on how can I search from this many to many relationships?
 - Custom QueryBuilder : will error "Iterate with fetch join in class ProductBundle\Entity\Product using association categories not allowed. "

**Comment by Clorr** [comment]
Hi @chanondb !
I encountered the same problem and replied here: https://github.com/omines/datatables-bundle/issues/30#issuecomment-673962858

If this solves your problem, feel free to close this issue (which is not an issue by the way ;-) )

**Comment by chanondb** [comment]
> Hi @chanondb !
> I encountered the same problem and replied here: [#30 (comment)](https://github.com/omines/datatables-bundle/issues/30#issuecomment-673962858)
> 
> If this solves your problem, feel free to close this issue (which is not an issue by the way ;-) )

Okie Thanks, Let me try to check this solution **'simple_total_query' => false** , currently using  distinct and a bit custom query. But Order column doesn't work properly  
`

                   'query' => function (QueryBuilder $qr) use($request) {

                    $param = $request->query->all();
					$qr->select('distinct p')
                    
                    ->addSelect('groupManager')
                    ->from(Product::class, 'p')
                    ->leftJoin("p.groupManager" ,"groupManager")
                    ->andWhere('p.deletedAt IS NULL');
                }
`

**Comment by curry684** [comment]
This is a Doctrine/DQL issue, not really for the bundle to fix   😉
