### ISSUE TITLE
Templates have various issues

### ISSUE THREAD

**Issue by skylord123** [omines/datatables-bundle#184]
So I see in various template files that `datatable.setting()` keeps getting called in despite the `DataTable` class having no method or even variable named `setting`. Why is this the case? Was this an update that just wasn't well thought through? The `Filter/text.html.twig` template file has the same issue by using variables and methods that don't actually exist.

Also why does the `datatable_html.twig.html` file have the column filters commented out? I am specifically using this bundle to help with the filtering of columns but have yet to get that even working because of these issues. Wasn't the 5.0 release supposed to have column filtering support? (it was specifically mentioned in the release notes)

It would have been nice if there was more examples of using this bundle. I would have loved to see an example showing how to use column/global filtering instead of me having to dig through the code and other issues to figure out how it works (and finding out it doesn't).

**Comment by curry684** [comment]
Columns searches were implemented in https://github.com/omines/datatables-bundle/pull/120 and are indeed not really documented. I'd recommend reading the issue (I haven't used them myself even so I'm no more knowledgeable here than you). Nobody had time or interest to write docs but it was confirmed that it worked, so it got merged   ;)  Bundles like this are not in a position to reject features if not perfectly documented, we'd get no updates at all.

As for the other issues I'm not really sure what you mean, the templates have always worked fine.

**Comment by numerogeek** [comment]
Hi @skylord123 do you have any information on how the filtering is working in this bundle ? indeed documentation is missing, and digging in the PR isn't helpful.. Thanks 👍

**Comment by skylord123** [comment]
> Hi @skylord123 do you have any information on how the filtering is working in this bundle ? indeed documentation is missing, and digging in the PR isn't helpful.. Thanks 👍

Honestly I ditched the bundle and just used my own controller code. I just kept running into limitations and bugs and needed to get something out asap.
