### ISSUE TITLE
Multiple DataTables on one template

### ISSUE THREAD

**Issue by bmeloski** [omines/datatables-bundle#186]
It is either not implemented or I don't understand how to do it. Multiple DataTables return values of only one table (if you have 2 entities mapped, request responds with only one dataset).

**Comment by MaximePinot** [comment]
If you want to display more than one DataTable on the same page, make sure to give each DataTable a unique name (default name is `dt`).

```php
$datatableOne = $dataTableFactory->createFromType(FirstTableType::class)
	->setName('datatable_one');

$datatableTwo = $dataTableFactory->createFromType(SecondTableType::class)
	->setName('datatable_two');
```

**Comment by bmeloski** [comment]
Thank you! it's working
