### ISSUE TITLE
ServerSide on false not displaying all results

### ISSUE THREAD

**Issue by viccvanco** [omines/datatables-bundle#188]
Hello,

I tried to pass serverSide property to false in my DataTable script, but it displays to me only 50 results when I have more than 30 000 entries in my table.

And when I pass serverSide property to true, I've got all my results to display.

What can explain this difference? How can I get all my results with serverSide property on false ?

Thank you.

**Comment by curry684** [comment]
serverSide must be true as it forced DataTables to fetch results via API. Without that, you only ever get a serverSide call for the first page, hence your results.
