### ISSUE TITLE
Extendability of classes is kind of reduced by using private on a lot of fields and functions

### ISSUE THREAD

**Issue by pkly** [omines/datatables-bundle#193]
Would it be possible to get most, if not all, fields changed to protected? Some classes like AutomaticQueryBuilder seem like something that could easily be extended, yet basically need to be copied into a different class to change anything because of how restricted they are.
There isn't much reason most of the functions and variables should be private, changing them to protected would simply make it easier to change parts of the code without rewriting everything from scratch.

**Comment by curry684** [comment]
We follow this vision: http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html

Protected functions and fields are an API. We're open to discussion on 'opening' parts of that API, but not as a blanket replace all private=>protected.
