### ISSUE TITLE
Custom search builder

### ISSUE THREAD

**Issue by tomas-kulhanek** [omines/datatables-bundle#195]
Hi, how is possible to use custom [search builder](https://datatables.net/extensions/searchbuilder/)? 

When i define in JS, the server is not search by these builder
![image](https://user-images.githubusercontent.com/7447745/96377832-93555680-1188-11eb-9d97-7c962ed19784.png)

**Comment by curry684** [comment]
The search builder is a clientside extension, and this bundle only aims for serverside integration, without obstructing clientside power. You can use the convenience functions provided by this bundle, or write all the JS yourself, enabling integration of every possible extension to DT.

**Comment by robiinho** [comment]
Hi, 

i developped a new SearchBuilderClassProvider.php that seems to do the job, if some is interested:
https://github.com/robiinho/datatables-bundle/tree/master

I also tried to do a pull request
