### ISSUE TITLE
Add support for opcache preloading

### ISSUE THREAD

**Issue by trandbert37** [omines/datatables-bundle#196]
Hi,
Opcache preloading seems not supported.
I have folling error:
message
`Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Error: Anonymous class wasn't preloaded" at /var/www/app/vendor/omines/datatables-bundle/src/Adapter/Doctrine/ORMAdapter.php line 329`
I am using Symfony 5.1.8 with PHP 7.4.11

I can give you more information if needed.

Alex

**Comment by curry684** [comment]
Upstream bug in PHP, already fixed.
