### ISSUE TITLE
addSelect vs rendring

### ISSUE THREAD

**Issue by doxt3r** [omines/datatables-bundle#199]
Hello,
I am trying to use an addSelect with an as statment, i can retrieve the value using the following code in the rendrer:

```
            ->add('account', TextColumn::class, ["label" => "Account",
                'render' => function(string $value, array $context){ return $context['account'];}])
```
How can concat the retrieved value of account with a string like:
`<a class="edit-element" href="/edit/%s"><i class="fa fa-edit"></i></a>`

Thank you

**Comment by curry684** [comment]
Just put it in the return and enable `raw` output.

https://omines.github.io/datatables-bundle/#textcolumn
