### ISSUE TITLE
Implement column-level searches

### ISSUE THREAD

**Issue by curry684** [omines/datatables-bundle#2]
Were broken during refactor, currently the `column_filters` option throws as it's not working.

**Comment by wesnick** [comment]
hi @curry684 ,
I would like column level filter/search for my project, so I have some time to put into addressing this.  Could you take a look at my PR and provide some feedback about the direction you would like me take with this?  I have made the minimal amount of changes needed to just get it to work for me.

**Comment by mcnjoshmartin** [comment]
How much work would it take to get this working?

**Comment by vaibhavpandeyvpz** [comment]
I have proposed a PR for this #120

**Comment by FigaCZ** [comment]
Any progress on this?

**Comment by citadev** [comment]
If you check the PR (#120) you'll see it's merged, it's available in the latest release.

**Comment by curry684** [comment]
And I should've closed this, it was indeed part of https://github.com/omines/datatables-bundle/releases/tag/0.5.0
