### ISSUE TITLE
info option is missing

### ISSUE THREAD

**Issue by barbuslex** [omines/datatables-bundle#201]
Hi,

I have set in datatables.yaml : 
```
datatables:
    options:
        info: false
```` 

So info options is not recognized by the bundle but correctly if i set it directly in javascript : 
```
$('#datatable').initDataTables({{ datatable_settings(datatable) }}, { "info": false });
```

Is it possible to add it in the bundle ?

Thanks

**Comment by curry684** [comment]
There is a philosophy there - we only allow serverside setting of options that make sense to have control of from the server side. `info` is a display option, and as such not supported. Setting it in the templates/JS is therefore the correct course of action.

I am aware that this philosophy can be considered flawed, and open to discussion on it, but it would have to be a wider discussion (`info` isn't the only option not supported).
