### ISSUE TITLE
Warning: Illegal string offset 'search', Warning: Illegal string offset 'column'

### ISSUE THREAD

**Issue by idealyhenintsoagithub** [omines/datatables-bundle#210]

**Comment by mxmilyasov** [comment]
I got the same error. Symfony has stopped rendering tables.

**Comment by maxhelias** [comment]
I think it's complicated to make the information shorter...

If you want the issue to go forward you're going to have to give more information and context about the warning.

**Comment by jenszahner** [comment]
I also ran into that problem, but I was able to fix is by downgrading to 0.5.1 
`symfony composer require 'omines/datatables-bundle:0.5.1`

**Comment by jenszahner** [comment]
I could trace down the error to DataTableState.php to the code accessing **$parameters->all(....)**. We are using Symfony 4.4.18 in our projects and symfony/http-foundation in 4.4.18 and the ParameterBag.php function all() does not support an optional parameter to all of the specified key.

**Comment by jkabat** [comment]
We had a discussion about a problem recently:

https://github.com/omines/datatables-bundle/commit/5ccdc1283ff1931c8259796447b8e69f48ea5302#r45847066

**Comment by simtrami** [comment]
@curry684 Is the active support of Symfony LTS 4.4 going to stop or do you plan on reverting to `ParameterBag::get()`?

**Comment by curry684** [comment]
https://github.com/omines/datatables-bundle/releases/tag/0.5.3

**Comment by curry684** [comment]
Let me know if it also fixes this specific issue.

**Comment by simtrami** [comment]
I just updated to v0.5.3, ordering no longer fails on Symfony 4.4.18. I can't confirm the same thing for searching right now, but I don't see why not.

**Comment by curry684** [comment]
👍
