### ISSUE TITLE
Thanks for breaking 4.4 compatibility

### ISSUE THREAD

**Issue by pkly** [omines/datatables-bundle#212]
0.5.2 lmao, why change something that works perfectly fine for multiple releases...
Not to mention that many sensible features aren't even in this bundle, we've had to modify a ton of it to basically get things to work (multi-join tables with searching and ordering, unsafe entity names and MORE)
I think I'll just end up forking the whole thing because this repo is barely working...

**Comment by maxhelias** [comment]
You are free to contribute to this bundle instead of complaining.
It's an open source project made on free time.

**Comment by Gerben321** [comment]
4.4 lmao.

Great job at being a dick at people that created this for you to freely use. Contribute to the package if you think it can be improved.

**Comment by curry684** [comment]
Ok.
