### ISSUE TITLE
How to set row classes?

### ISSUE THREAD

**Issue by JPustkuchen** [omines/datatables-bundle#223]
Hi and thank you very much for this great project!

I have a quite simple use-case but can't find a proper solution:
We need to set conditional classes on rows (date value > today ==> add class "negative" on row). Is there any concept for this? We're using the ArrayAdapter (which is also missing documentation in the Docs -> TBD).

**Comment by JPustkuchen** [comment]
As I didn't find a solution to this issue and also didn't require the AJAX functionality, which made it more complicated in my case, I decided to create https://github.com/JPustkuchen/TableClassBundle/ as a lightweight alternative. Perhaps it might help others.

If someone could still answer this question and provide a working example it would still be helpful.

Thanks a lot!

**Comment by jkabat** [comment]
@JPustkuchen you could easily do that with DataTables rowCallback:

- first setup condition on your column eg
```php
->add('highlight', BaseColumn\BoolColumn::class, [
    'data' => function (Call $context, $value): bool {
        return $context->isPremium();
    },
    'visible' => false,
]);
```
- then user rowCallback to add class based on condition
```javascript
$.fn.initDataTables.options = {
    rowCallback: function (row, data) {
        $(row).addClass('list-table-item');
        if (!data.hasOwnProperty('highlight')) {
            return;
        }
        if ('true' === data.highlight) {
            $(row).addClass('warning');
        }
    }
};
```

Please take a look at Datatables documentation.

**Comment by JPustkuchen** [comment]
Thank you very very much @jkabat - I didn't realize that this could be something to do in Datables itself, sorry! Thanks a lot for the code! :)
