### ISSUE TITLE
How can I pass the pagenr to the server

### ISSUE THREAD

**Issue by pluk77** [omines/datatables-bundle#225]
In order for the data that is coming back from a web-service to show in a data-table, we created our custom adapter. This all works wonderful, but now we have an API that requires us to provide it with the page nr instead of an offset / page-length.

Is there a way to pass the 'page-number' instead of or in addition to 'start' and 'length' back to the server as the user clicks on the pagination buttons at the bottom of the page?

Once this comes back from the client, we can extend the State object to include this new variable and use that to request the correct page from the API

**Comment by curry684** [comment]
Not really, we depend on the calls made by DataTables itself. This can only be patched on their end.
