### ISSUE TITLE
Export Excel just first line ?

### ISSUE THREAD

**Issue by SlimArfaaoui** [omines/datatables-bundle#236]
When i add export Excel server side i have just the first line in in the downloaded file.

So i followed a the problem i found you to limit the result. is there a reason or is a bug.

File : vendor/omines/datatables-bundle/src/Exporter/DataTableExporterManager.php

Code : 
/**
     * Browse the entire DataTable (all pages).
     *
     * A Generator is created in order to remove the 'DT_RowId' key
     * which is created by some adapters (e.g. ORMAdapter).
     */
    private function getAllData(): \Iterator
    {
        $data = $this->dataTable
            ->getAdapter()
            ->getData($this->dataTable->getState()->setStart(0)->setLength(-1))
            ->getData();

        foreach ($data as $row) {
            dd($data);
            if (array_key_exists('DT_RowId', $row)) {
                unset($row['DT_RowId']);
            }

            yield $row;
        }
    }

Solution : when i remove "setLength(-1)" i have what i want even if i sort.

**Comment by MaximePinot** [comment]
Hi @SlimArfaaoui,

`$this->dataTable->getState()->setStart(0)->setLength(-1)` : this is supposed to retrieve the entire table (otherwise it would only export the current page).

Are you able to reproduce your issue with a test case?

**Comment by SlimArfaaoui** [comment]
Hello @MaximePinot,

Yes i reproduce the error in a test case.
I think i see now whats is the problem : 
its about limit in MongoDB to get all data, the value to set no limit is not -1 like SQL is 0.

Can you please confirm this.
Thank you

**Comment by curry684** [comment]
This issue was actually fixed in the 'breaking changes' of the 0.7 release following #257 - we changed semantics for 'no limit' to the correct `null` instead of `-1` which was indeed adapter specific.

Adapters now all follow this rule and this issue should be fixed after that.
