### ISSUE TITLE
Passing additional data to the TwigColumn template render

### ISSUE THREAD

**Issue by bertoost** [omines/datatables-bundle#238]
Currently you can only render a Twig template and it passes the current row and the normal value to the template. It would be cool to have the ability to add more values to the view.

```php
$table->add('field', TwigColumn::class, [
    'template' => 'tenant/students/snippets/overview/courses.html.twig',
    'variables' => [             // <-- Add-in extra variables to the view
        'var' => 'value',
    ],
]);
```

**Comment by Ahummeling** [comment]
From my understanding, this is already possible:
```
$table->add('field', TwigColumn::class)->setTemplate('tenant/students/snippets/overview/courses.html.twig', ['var' => 'value']);
```
However, I do agree that it is strange that the `TwigColumn` does not support this by default, so I added a PR for the feature.  #254

**Comment by curry684** [comment]
@Ahummeling that is NOT the same. that code runs `setTemplate` on the DataTable instance, not the column. It overrides the rendering of the entire table.

**Comment by Ahummeling** [comment]
> @Ahummeling that is NOT the same. that code runs `setTemplate` on the DataTable instance, not the column. It overrides the rendering of the entire table.

Oh, I see. My bad, sorry! Thanks for clarifying
