### ISSUE TITLE
(ErrorException) Notice: Undefined index

### ISSUE THREAD

**Issue by hasanozbey** [omines/datatables-bundle#24]
Hello, all.
I am always getting this notice while trying to get some data from associated tables via ORMAdapter.  Exception page is pointing at line 266 from \ORMAdapter.php. I know there is something wrong with my field name but i don't know how to fix it. Need some enlightenment!

(ErrorException) Notice: Undefined index: type_id

Here is my controller sample:

```
$table = $this->createDataTable()->add('type_title', TextColumn::class, ['field' => 'type_id.title', 'label' => 'TESTING']);

$table->createAdapter(ORMAdapter::class, [
		'entity' => ShipInfo::class,
		'query' => function (QueryBuilder $builder) {
			$builder
				->select('s')
				->from(ShipInfo::class, 's')
				->orderBy('s.name', 'ASC')
				;
		},
])->handleRequest($request);
```
App\Entity\ShipInfo
```
/**
* @ORM\ManyToOne(targetEntity="App\Entity\ShipTypes", inversedBy="ships")
* @ORM\JoinColumn(name="type_id", referencedColumnName="id", nullable=false)
 */
 private $type_id;

public function getTypeId(): ?ShipTypes
    {
        return $this->type_id;
    }

// ...
private $name;
```
App\Entity\ShipTypes
```
public function __construct()
{
     $this->ships = new ArrayCollection();
}
/**
 * @ORM\OneToMany(targetEntity="App\Entity\ShipInfo", mappedBy="type_id")
 */
 private $ships;

/**
 * @return Collection|ShipInfo[]
 */
 public function getShips(): Collection
 {
     return $this->ships;
 }
// ...
private $title;
```
I've tried both "typeId.title" and "type_id.title" by the way.
Any help would be appreciated.

**ADDITION**

```
$table = $this->createDataTable()->add('type_id, TextColumn::class');
$table->createAdapter(
//...
)
```
Returning blank row. It is acting like "type_id" column is empty -- which is not.

**Comment by curry684** [comment]
Hey @hasanozbey,

Your DQL query does not join the `ShipTypes` entity so it does not get hydrated by Doctrine. Your query builder should look something like this:
```
$builder
				->select('s')
				->from(ShipInfo::class, 's')
				->join('s.type_id', 'type_id')
				->orderBy('s.name', 'ASC')
				;
```
Alternatively you could in this case just drop the query builder as the default ORM adapter will automatically try to join all references tables, you are disabling that by overriding the query builder yourself.

**Comment by hasanozbey** [comment]
Thank you so much for the info & this great repo!
