### ISSUE TITLE
How to change default page length?

### ISSUE THREAD

**Issue by bertoost** [omines/datatables-bundle#240]
I would like to know how to change the default page length of a table.. I found there is a method for this, but I can't find a way how to change this when using `$dataTableFactory->createFromType()`.

Like to hear. Thanks!

**Comment by maxhelias** [comment]
You can do that in the configuration with `datatables.options.pageLength` for a general usage or with the third parameters of `createFromType` with the key `pageLength`

**Comment by bertoost** [comment]
Wow! Thats works like a charm. Thanks!
