### ISSUE TITLE
Custom Adapter

### ISSUE THREAD

**Issue by cyrille-osyla** [omines/datatables-bundle#256]
Hello,

I would like to be able to add an adapter to point to a database other than Doctrine ORM and only play with Pure SQL queries (Prestashop Database).
Unfortunately in the doc I see TDB in the section: Implementing custom adapters

Is it possible ? If yes, how ?
Thank you

And congratulations again for this module which works perfectly in my case with Doctrine ORM :)

Best regards

**Comment by MaximePinot** [comment]
Hi @cyrille-osyla,

You can find an example here: [CustomORMAdapter](https://github.com/omines/datatables-bundle/blob/master/tests/Fixtures/AppBundle/DataTable/Adapter/CustomORMAdapter.php).

You can find a usage example here: [Grouped2TableType](https://github.com/omines/datatables-bundle/blob/87e006613f685a89dfc8d06a77bc75f004835e59/tests/Fixtures/AppBundle/DataTable/Type/Grouped2TableType.php#L38).

**Comment by cyrille-osyla** [comment]
Hi @MaximePinot,
Thanks for your feedback.
I'm having a little trouble figuring out how to pass the correct database and model-free entity.
Or should I create model entities in reverse engineering?

**Comment by curry684** [comment]
For writing your own adapter I recommend looking at the `ArrayAdapter` included (the most basic adapter possible) or indeed the `CustomORMAdapter` pointed at above. It's not terribly complex but also hard to document as it's barely ever needed and most if not all required code depends on the target.
