### ISSUE TITLE
Install doctrine/doctrine-bundle to use the ORMAdapter

### ISSUE THREAD

**Issue by bizou78** [omines/datatables-bundle#26]
Hi guy,

Thank you for your great work on this bundle, it's looking awesome.

Actually i'm trying this just for me and i have the errror "Install doctrine/doctrine-bundle to use the ORMAdapter". And i don't understand why.

doctrine/doctrine-bundle is already in my appkernel.php, so i don't understand why it's not working.

You can show my code below.

AppKernel.php 

`$bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new \Omines\DataTablesBundle\DataTablesBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
        ];`

and here my controller where i try to create a dataTable

`public function indexAction(Request $request)
    {
        $table = new DataTable();
        $table
            ->add('firstname', TextColumn::class)
            ->add('lastname', TextColumn::class)
            ->add('email', TextColumn::class)
            ->add('phone', TextColumn::class)
            ->add('age', TextColumn::class)
            ->createAdapter(ORMAdapter::class, [
                'entity' => User::class]
            );

        $table->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }

        return $this->render('dataTableIndex.html.twig', ['dataTable'=>$table]);
    }`

Best regards

**Comment by giovannialbero1992** [comment]
Hi, can you provide more details?
Symfony version, datatables-bundle version, etc.

Thanks!
-- 
*Giovanni Albero*
+393661860916
giovannialbero.solinf@gmail.com
full-stack developer
Skype: giovanni.albero
Linkedin: https://it.linkedin.com/pub/giovanni-albero/64/465/bba
Twitter: @albero92

**Comment by curry684** [comment]
As noted in the docs:

> After installation, if not using Flex, you should register the bundle to your kernel, commonly AppKernel.php, before your own bundles but after the required external bundles, such as FrameworkBundle and TwigBundle.

You are currently loading DoctrineBundle after ours, and as it registers the `doctrine` service alias during compilation that we depend on to inject into the adapter this makes it sensitive to order of loading.

I believe this was fixed in Symfony 4 due to how Flex works.

**Comment by giovannialbero1992** [comment]
Do you have `doctrine` service in your container (you can do a check in a controller)? Try to add to your `service.yaml`
```yaml
doctrine:
    alias: 'doctrine.orm.default_entity_manager'
```

**Comment by bizou78** [comment]
ok , i don't know what happen, i just test an array Adapter this morning and when i came back on ORMAdapter the error has disapear.

And i also disable all datatable config in my config.yml.

Now i try to display my table but i don't now if i need to make a template or if the bundle construct the table :)

Sorry for my beginner questions :)

best regards

**Comment by bizou78** [comment]
i think i need to sleep, i just forgot to load JQUERY in my project...

Thank's a lot for your help, all is fine now.

Best regards

**Comment by curry684** [comment]
Lol ok, good to hear it's fixed 🎉
