### ISSUE TITLE
Can the table be displayed as a form?

### ISSUE THREAD

**Issue by rubeendaw** [omines/datatables-bundle#265]
Hello everyone, I have been researching and implementing this table for a few days.

I wish I could do this
https://datatables.net/examples/api/form.html

It's possible? or do I have to do the whole implementation?

**Comment by curry684** [comment]
That example runs completely clientside, and this bundle is unopinionated on what you do on that end. So yes, you can implement this by writing your own frontend code to do it.

https://omines.github.io/datatables-bundle/#javascript explains how to do all customization in JS.
