### ISSUE TITLE
problem with stateSave: true 

### ISSUE THREAD

**Issue by biji** [omines/datatables-bundle#27]
Using option `stateSave: true` , state is saved, but after reload page, 1st page show not related to saved state
I also set `persist_state: none` in datatables.yml

Thanks

**Comment by mmaglia** [comment]
Hi. It happens the same to me too. I don't understand why this issue has been closed. I have tried configuring with the `persist_state: "local"` option and in my JS the `stateSave: true` option and every time I reload, the Datatable is initialized as if it were loaded for the first time. I have been able to verify that the local storage is working properly.
