### ISSUE TITLE
Get JS instance of datatable

### ISSUE THREAD

**Issue by ArmandArthur** [omines/datatables-bundle#303]
Hello,

Can you tell me how retrieve the instance of datatable in Javascript?

Thanks you

**Comment by curry684** [comment]
It's actually in the docs: https://omines.github.io/datatables-bundle/#javascript

**Comment by ArmandArthur** [comment]
$("#id").DataTable()

**Comment by curry684** [comment]
That will not work until the initialization is completed, which is why using the Promise is recommended practice.
