### ISSUE TITLE
Exporter should set MIME type

### ISSUE THREAD

**Issue by gmta** [omines/datatables-bundle#316]
In the `BinaryFileResponse` for an export, the MIME type should be set here if the exporter is able to provide it (which is usually the case):
https://github.com/omines/datatables-bundle/blob/01cec9a8ff2bbd92384b1210d5cb8b5c21aceef5/src/Exporter/DataTableExporterManager.php#L65-L77

This allows applications to skip MIME detection and enables running without the optional `symfony/mime` package.

**Comment by curry684** [comment]
PR welcome, I made a point of not touching the export code myself   😆

**Comment by gmta** [comment]
@curry684 should be easy enough, but the nicest solution (adding a method to the exporters) would require a backwards incompatible change to `DataTableExporterInterface` since it is a public interface.

Would this be OK or is there another approach you'd prefer?

**Comment by curry684** [comment]
Given that 0.8 is already severely breaking and in RC since this week I'm fine with a BC break (https://github.com/omines/datatables-bundle/releases/tag/0.8.0-rc.1)

**Comment by curry684** [comment]
Any progress?
