### ISSUE TITLE
Working with PHP Enums

### ISSUE THREAD

**Issue by craigh** [omines/datatables-bundle#317]
I am struggling to create a column where the property is configured as an enum value. To be clear, the database simply stores a varchar but the **Doctrine entity** defines the property an enum. It appears that this library is attempting to convert the value to a string too early in the process.

Entity:
```php
    #[ORM\Column(length: 2, enumType: USState::class)]
    protected USState $state;
```

Datatable:
```php
            ->add(
                'state',
                TextColumn::class,
                [
                    'label' => 'State',
                    'render' => fn (USState $state) => $state->value,
                ]
            )
```

I get an exception:

`Object of class App\Enum\USState could not be converted to string`

It never reaches the `render` stage. Any ideas here?

**Comment by craigh** [comment]
```php
<?php

declare(strict_types=1);

namespace App\Datatables\Column;

use Omines\DataTablesBundle\Column\AbstractColumn;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnumColumn extends AbstractColumn
{
    public function normalize($value): string
    {
        if (empty($value)) {
            return '';
        }
        if ($value instanceof $this->options['class']) {
            return $value->value;
        }
        throw new \InvalidArgumentException('Class must be of type BackedEnum');
    }

    protected function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver
            ->setDefault('class', \BackedEnum::class)
            ->setAllowedTypes('class', 'string')
        ;

        return $this;
    }
}
```

**Comment by curry684** [comment]
I was just about to post "You should create an EnumColumn in which you override the `normalize` method, but I see you figured it out  ;)

I'll happily merge a PR adding the EnumColumn in a futureproof way (PHP didn't have enums when we originally developed the bundle).

**Comment by craigh** [comment]
> I'll happily merge a PR adding the EnumColumn in a futureproof way (PHP didn't have enums when we originally developed the bundle).

Since your next version of the bundle (0.8) breaks semver and requires php >=8.1 (and Symfony ^6.3) it seems a future-proof method wouldn't be necessary.

**Comment by curry684** [comment]
We're not breaking semver, major version 0 is an [exception case](https://semver.org/#spec-item-4) on purpose and Composer considers the minors to be breaking.

**Comment by craigh** [comment]
@curry684 sure 😄 but it could be argued that a project that has been in the public since 2017 and is well used (and liked) and now seeing greater use with the abandonment of sg/datatables probably should be at at least version 1.0.0 for some time. In any case, the new requirements of version 0.8 will not allow us to use it as the project I work on is still at php 8.1 and Symfony 5.4. I guess I am stuck with v0.7 for now. Out off curiosity, what prompted the new requirements?

**Comment by craigh** [comment]
I appreciate the discussion. Please don't misunderstand my thoughts for criticism. I appreciate the bundle (and your work maintaining it) and hope it lives on 😄 

ftr, apparently datatables can be used without jQuery https://datatables.net/manual/installation (Non-jQuery initialisation)

**Comment by althaus** [comment]
> ftr, apparently datatables can be used without jQuery https://datatables.net/manual/installation (Non-jQuery initialisation)

I'm pretty sure that DT is still using jQuery under the hood. Only the initilization can be done without it.

**Comment by curry684** [comment]
> I'm pretty sure that DT is still using jQuery under the hood. Only the initilization can be done without it.

Yep, it just bundles it in 'independent' mode, without relying on jQuery globals.

They've been trying literally for over 5 years to get rid of it: https://datatables.net/forums/discussion/51702/non-jquery-version-of-datatables-is-this-gonna-happen
