### ISSUE TITLE
Uncaught TypeError: $(...).initDataTables is not a function

### ISSUE THREAD

**Issue by jrobinsonadrenaline** [omines/datatables-bundle#32]
Following the instructions at [https://omines.github.io/datatables-bundle/](url) I have installed with composer, configured the options in my config.yml, added the controller code, passed the object to the template, and added the datatable_settings() twig filter within script tags as instructed (wrapped in a $(function) block. I am getting a jQuery error: $(...).initDataTables is not a function, and i do have all the dependencies in the {% block javascripts %}{% endblock %} (in the correct order). I am not compressing with assetic (or anything else, not that it would be an issue I'm sure). It appears I have followed the instructions exactly, but I'm guessing I am missing something minor, any assistance is appreciated!

Symfony 3.3.* 
Datatables 1.10.15
jQuery 3.1.1

**Comment by curry684** [comment]
You need to run `bin/console assets:install` or whatever your project requires to install the supplied Javascript file containing that function.

**Comment by curry684** [comment]
Nothing left to do so closing.
