### ISSUE TITLE
Disable the softdeleteable filter for a specific datatable

### ISSUE THREAD

**Issue by saturit** [omines/datatables-bundle#320]
Hi.
Is there any way to disable the softdeleteable filter for a specific datatable? I'm trying to disable it, but obviously it doesn't work via ORMAdapter.  I have no idea whether this is a bug or a focus.

**Comment by roublarstar** [comment]
Hi,
you could use the "ORMAdapterEvents::PRE_QUERY" event to access the entity manager and deactivate the doctrine behavior. However, there is no "ORMAdapterEvents::POST_QUERY" event.
But I think it does the job, only the ajax call will be impacted by this deactivation.
![image](https://github.com/omines/datatables-bundle/assets/12220452/8909415e-55f3-4b2c-9e13-04b6593e0ed2)
