### ISSUE TITLE
Since symfony/dependency-injection 7.2: Type "tagged" is deprecated

### ISSUE THREAD

**Issue by Chris53897** [omines/datatables-bundle#362]
`Since symfony/dependency-injection 7.2: Type "tagged" is deprecated for tag <argument>, use "tagged_iterator" instead in "/xxx/vendor/omines/datatables-bundle/src/DependencyInjection/../Resources/config/services.xml".`

https://github.com/omines/datatables-bundle/blob/master/src/Resources/config/services.xml

I will try to find some time to create a PR.

**Comment by curry684** [comment]
Please do doublecheck when they were introduced - the bundle supports 6.4 LTS and they were added around that time I believe.

**Comment by curry684** [comment]
Nevermind, was an inplace fix.
