### ISSUE TITLE
Error when language_from_cdn false and url contain query/fragment

### ISSUE THREAD

**Issue by biji** [omines/datatables-bundle#40]
if `language_from_cdn: false` and url contains query/fragment, this error throwed:
`TypeError: dt.state is not a function`
It seem `dt` not yet initialized but it require ajax for option

**Comment by aaronfessler** [comment]
Thank you for this fix!

**Comment by curry684** [comment]
Tagged in https://github.com/omines/datatables-bundle/releases/tag/0.4.1 now.
