### ISSUE TITLE
Issue: Buttons are not appearing when defined in the DOM option

### ISSUE THREAD

**Issue by technical1000heads** [omines/datatables-bundle#44]
Hi all, I am attempting to include the button options on some of my tables yet when applying the DOM options as per this link: https://omines.github.io/datatables-bundle/#javascript

Details:
Symfony 4.1
Omines DataTable: 0.2.0
PHP: 7.1

I get no buttons appearing on the page, but also no errors.

Sample code from one of the tables:

```
$('#gimmebrows').initDataTables({{ datatable_settings(datatable) }}, {
                searching: true,
                dom: 'BlTfgitp',
                buttons: ['copy'],
                order: [10, 'desc']
});
```

It also does not work with the code as per the example in the docs:

```
dom:'<"html5buttons"B>lTfgitp',
    buttons: [
        'copy',
        { extend: 'pdf', title: 'domains'},
        { extend: 'print' }
 ]
```

Any insights, or if there is an updated method would be appreciated.

**Comment by MaximePinot** [comment]
Hi,

One possible reason is that you may have forgotten to download the [Buttons extension](https://www.datatables.net/extensions/buttons/).

**Comment by technical1000heads** [comment]
I'll give adding them separately a try. 

As a side note, is it not packaged up in the Omines bundle then? My thought would be if it's in the docs then it is (or should be), and it doesn't specifically state you need to download them that I can see.

**Comment by MaximePinot** [comment]
Neither the Buttons extension nor the DataTables jQuery plug-in itself is packaged up in the Omines bundles as they are clientside dependencies.

**Comment by technical1000heads** [comment]
Thanks, I will give it a try then.

**Comment by technical1000heads** [comment]
Solutions was as above, including the individual files from here worked:

https://datatables.net/download/release

**Comment by curry684** [comment]
This is actually documented at https://omines.github.io/datatables-bundle/:

> All serverside dependencies are managed by Composer. Clientside dependencies are left up the implementer to decide how to include which DataTables dependencies. As long are you are using a fairly up to date version of DataTables you should be fine, as the bundle does not use exotic features or depend on plugins.
>
> The code snippets here should get you started quickly, including jQuery 3. For more extensive download options visit https://datatables.net/download/.
