### ISSUE TITLE
Add Another options

### ISSUE THREAD

**Issue by elfarqy** [omines/datatables-bundle#46]
When i try to add `deferRender` options, an error occurs. Even though [`deferRender` feature](https://datatables.net/reference/option/deferRender) available in datatables documentation

```The option "deferRender" does not exist. Defined options are: "autoWidth", "displayStart", "dom", "fixedHeader", "jQueryUI", "lengthChange", "lengthMenu", "order", "orderCellsTop", "ordering", "pageLength", "paging", "pagingType", "processing", "search", "searchDelay", "searching", "serverSide", "stateSave".```

**Comment by MaximePinot** [comment]
Hi,

As stated in the documentation (see: https://omines.github.io/datatables-bundle/#configuration) :
> Only options which are meaningful to be defined serverside can be set at this level, so setting callbacks and events is not possible. These are however easily set on the Javascript end.

You need to do this : 
```javascript
$('#dt').initDataTables({{ datatable_settings(datatable) }}, {
    deferRender: true,
});
```

**Comment by curry684** [comment]
Thank you @MaximePinot for providing the correct and swift answer   😄
