### ISSUE TITLE
How to display array field?

### ISSUE THREAD

**Issue by forexknight** [omines/datatables-bundle#50]
Hi,

I want to know how could I display serialized field - for example roles which are serialized in db for UserEntity. For now I did it by a trick, but there should be some way to do it.

Temporary fix:
```
public function normalize($value): string
    {
        if (is_array($value)) $value = implode(', ', $value); //added
        $value = (string) $value;

        return $this->isRaw() ? $value : htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE);
    }
```

**Comment by curry684** [comment]
Check the example next to the columns docs: https://omines.github.io/datatables-bundle/#columns
```
$table
    ->add('firstName', TextColumn::class, ['label' => 'customer.name', 'className' => 'bold'])
    ->add('lastName', TextColumn::class, ['render' => '<strong>%s</strong>', 'raw' => true])
    ->add('email', TextColumn::class, ['render' => function($value, $context) {
        return sprintf('<a href="%s">%s</a>', $value, $value);
    })
;
```
If the field is actualy an array you could use the `render` function to format it:
```
    ->add('someArrayValue', TextColumn::class, ['render' => function($value, $context) {
        return implode(', ', $value);
    })
```

**Comment by forexknight** [comment]
I have tried to use it like you said, I mean I did it exactly like you: 

```
   ->add('roles', TextColumn::class, ['render' => function($value, $context) {
        return implode(', ', $value);
    })
```
And then I received **array to string conversion error** - I think that before render method datatables wants to do something with those roles, but I did not continue the investigation.

**Comment by curry684** [comment]
It would help to have the callstack to there to actually know where it is trying to do what.

**Comment by forexknight** [comment]
I have datatable created associated with User entity.
I have serialized roles in my database via PHP serialize method.
Then this column provides error - Array to string conversion: 
```
->add('roles', TextColumn::class, ['render' => function($value, $context) {
        return implode(', ', $context->getRoles());
    })
```

**Comment by curry684** [comment]
I really need a call stack for this.
