### ISSUE TITLE
Question: use of tabs

### ISSUE THREAD

**Issue by D4rkPh0en1x** [omines/datatables-bundle#54]
Hi
Is it possible to use tabs together with your package?

Like in the example here:
https://datatables.net/examples/api/tabs_and_scrolling.html

**Comment by curry684** [comment]
Sure, those are just clientside tabs, we are completely agnostic to that. Just have 2 instances of the table and figure it out clientside.

This bundle *only does serverside magic*. All we do on the client side is a bit of convenience.
