### ISSUE TITLE
Implement client-side tables

### ISSUE THREAD

**Issue by curry684** [omines/datatables-bundle#6]
Currently every table will be serverside AJAX, which may be overkill or even explicitly undesired in certain cases. By inline invoking the Adapter we should be able to easily implement a full clientside table as well using DataTables.

**Comment by curry684** [comment]
There is no viable PR available and we are not actively developing this feature or planning to.

**Comment by JPustkuchen** [comment]
Thank you @curry684 - if others are looking for a solution without AJAX, like me, this might be an alternative: https://github.com/JPustkuchen/TableClassBundle/

In the README I described how to optionally use it with DataTables. When using DataTables WITH AJAX, this omines/datatables-bundle project is still perfect :)

**Comment by curry684** [comment]
In general we ourselves now mainly using Vue for fully clientside tables  :)   The issue more or less got caught up by technology.
