### ISSUE TITLE
Access to entity fields in table builder

### ISSUE THREAD

**Issue by graferowy** [omines/datatables-bundle#66]
Hi!
What is the best way to acess all of the entity fields in my table builder?
I've created seperate file implementing DataTableTypeInterface where I build my table I want to display using ORMAdapter.  There problem is when using render field option. The $context variable holds only fields I have added to the table, the rest are set to null.
Should I add a column with the field I want to access and set its visibility to false? Or is there a better way?

For example, here I would not have access to username field of my user entity.

```
class UsersTableType implements DataTableTypeInterface
{
    public function configure(DataTable $dataTable, array $options)
    {
        $dataTable
            ->add('id',
                TextColumn::class,
                array(
                    'label' => 'ID',
                    'render' => function ($value, $context) {
			return $context->getUserName(); }
                )
            )
	->createAdapter(ORMAdapter::class, [
                'entity' => Coupon::class
	]
    }
}

```

**Comment by curry684** [comment]
If you [create a custom query](https://omines.github.io/datatables-bundle/#doctrine-orm) you will no longer be limited to the fields displayed by columns. The default query builder will select just the fields referenced by columns, once you switch to a custom query you're completely in control about what to do. And of course that entire object will then be passed as the `$context`.

**Comment by graferowy** [comment]
Thank you very much. Works perfectly.
