### ISSUE TITLE
Finish ArrayAdapter

### ISSUE THREAD

**Issue by curry684** [omines/datatables-bundle#7]
It currently does not support column-level searches or ordering, and paging does not work correctly when doing a global search (page is taken before filtering instead of after).

**Comment by grudda** [comment]
Hi, why is this issue actually closed? The ArrayAdapter still doesn't perform sorting, filtering and paging correctly as stated initially here. Will be there progress any time soon?

**Comment by curry684** [comment]
It's not closed, the referenced issue is closed.

We are currently not actively investing efforts in parts of the bundle we do not use internally, this issue is more or a "missing feature tracker". Everyone's free to help with it.

**Comment by grudda** [comment]
Oh, you are absolutely right. Somehow I oversaw which one is closed, maybe I was so disappointed that the ArrayAdapter part is that unfinished. That's one of the reasons why we decided to integrate datatables natively in our application. Nevermind, thanks for your reply.
