### ISSUE TITLE
ArrayAdapter renders value twice

### ISSUE THREAD

**Issue by thijswiersema** [omines/datatables-bundle#70]
I was just trying out the bundle, seems promising. But I encountered a little bug on my first test setup.

The column ArrayAdapter is transforming and rendering the value twice. It appears to happen in the processRow function here https://github.com/omines/datatables-bundle/blob/37aaf560baabc8c621bfb6ae308eaa8933a85da1/src/Adapter/ArrayAdapter.php#L91

Seems to me the call on L101 is unnecessary.

**Comment by shades684** [comment]
You're right, but as stated in issue #7 the ArrayAdapter is far from completed.

**Comment by ceininger** [comment]
Hello @curry684 is it possible to have a new release with this fix inclued. I'm facing a problem with DateTimeColumn and nullValue fallback getting transformed twice (and then fail because the 2nd time, $value is a string).

**Comment by curry684** [comment]
Fair enough https://github.com/omines/datatables-bundle/releases/tag/0.3.0

**Comment by ceininger** [comment]
Thanks a lot :)
