### ISSUE TITLE
<table> instead <div> on table's placeholder

### ISSUE THREAD

**Issue by Fasterpast** [omines/datatables-bundle#74]
Hi, here [https://datatables.net/manual/tech-notes/2](url) you can see that using `<table> `tag in HTML code is obligatory with DataTables, however when i'm changing `<div>` tag (from example and which works fine) `<div id="presidents">Loading...</div>`  to `<table>` the table becomes unloadable. 
I want to use `<table>` because such constructions (enabling extensions on client-side)
`var table = $('#table').DataTable();`
throw errors which described on page above.

**Comment by Fasterpast** [comment]
You should post an issue to realize how it works ))
In all client side extensions I should use `dt` variable to make it work.

Sorry...

**Comment by curry684** [comment]
Awesome if an issue solves itself   😉
