### ISSUE TITLE
Invalid Boolean parsing from 

### ISSUE THREAD

**Issue by laurentmuller** [omines/datatables-bundle#78]
When parsing Parameters to create a DataTableQuery, the values (like 'searchable' or 'orderable') are cast to a boolean with code like:

`(bool) $column['orderable']`

But the parameter value can only be the literal `'true'` or `'false'` and when cast, it returns `true`.

A bug  fix is to test the literal value with code like:

` 'true' === $column['orderable']`

or

`filter_var($column['orderable'], FILTER_VALIDATE_BOOLEAN)`

Tested with Symfony v3.4.24 and PHP v7.2.14.

**Comment by curry684** [comment]
What problem would this fix?

**Comment by MaximePinot** [comment]
Hi,

When are these values `string`?

https://github.com/omines/datatables-bundle/blob/33fb34a71705f92c11e689f70c74e378ce57e44d/src/Column/AbstractColumn.php#L135-L138

**Comment by curry684** [comment]
I am aware of how type juggling and casting work in PHP, but as shown above those properties can never contain string values, as enforced by the [Symfony OptionsResolver component](https://symfony.com/doc/current/components/options_resolver.html). The `null` fallbacks are sane defaults also returning in correct boolean values.

https://github.com/omines/datatables-bundle/blob/33fb34a71705f92c11e689f70c74e378ce57e44d/src/Column/AbstractColumn.php#L206-L220

**Comment by laurentmuller** [comment]
Sorry, sorry and again sorry.

I wrote this issue in the wrong repository !

**Comment by curry684** [comment]
Right  😆
