### ISSUE TITLE
Can't use two datatables in same route

### ISSUE THREAD

**Issue by laurentk6** [omines/datatables-bundle#96]
Hello,

I'm trying to create two datatables with different data on the same route, but both tables are exactly the same (with the same data).
Is there a function or trick to display two datatables with two different entities ?

Exemple : 

` /**
     * @Route("/societe/new", name="society_create")
     * @Route("/societe/{id}/edit", name="society_edit")
     */
    public function form(Society $societe = null, ObjectManager $manager, Request $request){
        $table_address = null;
        $table_contact = null;

        if(!$societe){
            $societe = new Society();
        }else{
            $table_address = $this->createDataTableFromType(AddressTableType::class)
            ->handleRequest($request);

            if ($table_address->isCallback()) {                
                return $table_address->getResponse();                
            }

            $table_contact = $this->createDataTableFromType(ContactTableType::class)
            ->handleRequest($request);            

            if ($table_contact->isCallback()) {
                return $table_contact->getResponse();                
            }
            
        }

        $form = $this->createForm(SocietyType::class, $societe);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) { 
           
            $manager->persist($societe);
            $manager->flush();

            return $this->redirectToRoute('society');
        }

        return $this->render('society/create.html.twig', [
            'formSociety' => $form->createView(),
            'editMode' => $societe->getId() !== null,
            'datatable_address' => $table_address,
            'datatable_contact' => $table_contact,
        ]);

    }`

and datatabletypeInterface : 

`class ContactTableType implements DataTableTypeInterface
{

    public function configure(DataTable $dataTable, array $options){
        $dataTable
            ->add('firstname', TextColumn::class, ['label' => 'firstname'])
            ->add('lastname', TextColumn::class, ['label' => 'lastname'])
            ->add('id', TextColumn::class, ['label' => 'Action', 'render' => function($value, $context){
                return sprintf('<a href="/contact/%s/edit" class="btn btn-success">Modifier le contact</a>', $value, $value);
            }])
            ->createAdapter(ORMAdapter::class, [
                'entity' => Contact::class,
            ]);
    }
}`

`class AddressTableType implements DataTableTypeInterface
{

    public function configure(DataTable $dataTable, array $options){
        $dataTable
            ->add('name', TextColumn::class, ['label' => 'Nom'])
            ->add('address', TextColumn::class, ['label' => 'Adresse'])
            ->add('id', TextColumn::class, ['label' => 'Action', 'render' => function($value, $context){
                return sprintf('<a href="/societe/%s/adresse/%s/edit" class="btn btn-success">Modifier l\'adresse</a>', $value, $value);
            }])
            ->createAdapter(ORMAdapter::class, [
                'entity' => Address::class,
            ]);
    }
}`

Thanks for help

**Comment by MaximePinot** [comment]
Hi,

You have to set a unique name per DataTable.

Check [this file](https://github.com/omines/datatables-bundle/blob/master/tests/Fixtures/AppBundle/Controller/HomeController.php) for a complete example. 

The important line is: 
https://github.com/omines/datatables-bundle/blob/47261b3170804af8506eafc8ba40920141f121a9/tests/Fixtures/AppBundle/Controller/HomeController.php#L40

**Comment by laurentk6** [comment]
Thank you very much ! Works great !
