### ISSUE TITLE
Option to handle 500 requests.

### ISSUE THREAD

**Issue by olvenmage** [omines/datatables-bundle#98]
Datatables normally has an option under ajax called "error" in which you can handle errors. I would like to somehow configure this since we use oauth to send our requests, but this can throw an error (such as the token being revoked). Can we get an option to handle 500's?

I can obviously configure this manually for every datatable, but I would like some global way of altering the options. Maybe just a service decorator that mutates the options?

**Comment by curry684** [comment]
This bundle is not opinionated on the client side of handling errors, if only because an unauthenticated request should return a 403 response, not 500. I would recommend wrapping your client-side datatable code to perform global initialization duties.
